### ISSUE TITLE
Error when presto_enable = true

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#358]
```
Render template: 'templates/docker-compose.yml.j2' --> 'destination/docker-compose.yml'
Loading file '/opt/mdps-gen/templates/docker-compose.yml.j2'...
  Error while rendering template: Undefined variable: 'presto_etc_dir' is undefined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker_compose_templer/jinja_renderer.py", line 76, in render_string
    return cls.env.from_string(template_string).render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 6022, in top-level template code
jinja2.exceptions.UndefinedError: 'presto_etc_dir' is undefined

During handling of the above exception, another exception occurred:
```

**Comment by gschmutz** [comment]
seems to fixed already
