### ISSUE TITLE
Problem with Cassandra cluster

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#602]
```bash
root@cassandra-1:/# nodetool status
error: Authentication failed! Credentials required
-- StackTrace --
java.lang.SecurityException: Authentication failed! Credentials required
        at java.management/com.sun.jmx.remote.security.JMXPluggableAuthenticator.authenticationFailure(Unknown Source)
        at java.management/com.sun.jmx.remote.security.JMXPluggableAuthenticator.authenticate(Unknown Source)
        at org.apache.cassandra.utils.JMXServerUtils$JMXPluggableAuthenticatorWrapper.authenticate(JMXServerUtils.java:315)
        at java.management.rmi/javax.management.remote.rmi.RMIServerImpl.doNewClient(Unknown Source)
        at java.management.rmi/javax.management.remote.rmi.RMIServerImpl.newClient(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
        at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
        at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by gschmutz** [comment]
change `LOCAL_JMX` to `yes` by making it configurable.

**Comment by johnfelipe** [comment]
yes, tnks 
this already done

**Comment by gschmutz** [comment]
what do you mean by already done?

**Comment by johnfelipe** [comment]
change LOCAL_JMX to yes by making it configurable.
with that is solved
